### ISSUE TITLE
Verse Numbering Formatting

### ISSUE THREAD

**Issue by Llewellynvdm** [getbible/txtFactory#5]
The needed verse structure should be

```
01O||1||1||In die begin het God die hemel en die aarde geskape.
```

At the moment it in some translations results in

```
01O||1||1||10||In die begin het God die hemel en die aarde geskape.
```

So we need to remove the last number `10||` from the line.

**Comment by Llewellynvdm** [comment]
I just found that in the `Greek__OT_LXX_Unaccented__lxxunaccents__LTR.txt` it adds a || and the beginning of the first line.

**Comment by Llewellynvdm** [comment]
Silly question... does the `||` instead of `\t` work better in the text separation?

I said lets use the `||` but is it ideal or not really? (could be a major change to the rope)

But I want to do this in a way that it really works best for all not just for some...

**Comment by Llewellynvdm** [comment]
Hmmm @camilstaps  I thought I had it resolved this, but I now get similar error in the  `Armenian__Armenian_(Eastern)_(Genesis_Exodus_Gospels)__easternarmenian__LTR` version.

```
01O||1||1||01O||1||1||
```

So it is a little divergent from the previous issue, but at the same line of code.

**Comment by Llewellynvdm** [comment]
They have two index, sets like so

```
01O 1   1   01O 1   1       10  
```

one for nrsva and one for orig

This is displayed in the `#columns` string of each file, what do you think will it not make more sense to first get this columns string and then build the file selection based on it?

Let me know...

**Comment by camilstaps** [comment]
I think we always need the first three columns (and the last). If this is true, we don't need to read the columns string. This is a comment, so it may not be spelled exactly the same in every file.

I didn't check extensively.

**Comment by Llewellynvdm** [comment]
Okay I tried this

``` bash
cat armenian_eastern_utf8.txt | awk '{print $1"||"$2"||"$3"||"$NF}'
```

But it does not get the whole last column... any ideas @camilstaps

**Comment by camilstaps** [comment]
This commit simply takes the first three and the last columns.

**Comment by camilstaps** [comment]
I just checked all files, they seem to be fine (at least for the format). The versions below have empty lines at the beginning:
- Czech, KMS
- Czech, NKB
- Gothic
- Russian, Victor Zhuromsky
- Swahili
- Uma

So they seem incorrect, but if you check the original file, they have the same empty lines.

**Comment by Llewellynvdm** [comment]
Thanks @camilstaps that works great.... I know it's ugly but it get's the job done :+1:
